BEGIN;

CREATE SCHEMA IF NOT EXISTS projet;

CREATE TABLE user(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nom varchar NOT NULL,
    prenom varchar NOT NULL,
    email varchar NOT NULL,
    admin boolean NOT NULL DEFAULT FALSE
   );

CREATE TABLE rdv(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    debut date,
    fin date,
    description varchar,
    user_id integer
    );

COMMIT;
